/*
 * Generated by can_node.py. Do not manually edit this file.
 */

#include <stdint.h>
#include <stdbool.h>
#include "stm32f4xx_hal.h"
#include "stm32f4xx_hal_can.h"
#include "task/task_can_bus.h"
#include <shared_can_defs.h>
#include <string.h>
#include <gpio.h>
#include "util.h"
#include "subscribe.h"

CAN_MSG_placeholder_T m_CAN_MSG_placeholder;
uint32_t placeholder_rx_time;

void eat_new_data(CAN_rx_t* recv)
{
    set_led_2(true);
	void* dest = 0;
	uint32_t* time_address = 0;

	if (recv->header.ExtId == CAN_ID_placeholder)
	{
		dest = &m_CAN_MSG_placeholder;
		time_address = &placeholder_rx_time;
	}

	if (dest != 0) {
		memcpy(dest, &(recv->data), recv->header.DLC);
		*time_address = get_timestamp();
	}
}
