/*
 * Generated by can_configuration.py. Do not manually edit this file.
 */

#ifndef LHRE_SHARED_CAN_DEFS_H_
#define LHRE_SHARED_CAN_DEFS_H_

#include <stdint.h>

#define CAN_BITRATE (500000)

#define CAN_PRIORITY_LEVEL_TIME_CRITICAL (0)
#define CAN_PRIORITY_LEVEL_HIGH (1)
#define CAN_PRIORITY_LEVEL_NORMAL (2)
#define CAN_PRIORITY_LEVEL_LOW (3)
#define CAN_PRIORITY_LEVEL_DEBUG (4)

#define CAN_MAX_PRIORITY_LEVEL (4)
#define CAN_NUM_PRIORITY_LEVELS (5)

#define CAN_NODE_ID_BMS (0)
#define CAN_NODE_ID_INVERTER (1)
#define CAN_NODE_ID_VCU (2)

// Messages from node (0): BMS
#define CAN_ID_DRIVE_STATE (0x3000000)
#define CAN_PERIOD_DRIVE_STATE (0)
typedef struct __attribute__((__packed__)) {
	uint8_t state;
} CAN_MSG_DRIVE_STATE_T;


#define CAN_ID_IMD_status (0x69)
#define CAN_PERIOD_IMD_status (0)
typedef struct __attribute__((__packed__)) {
	uint32_t frequency;
} CAN_MSG_IMD_status_T;


#define CAN_ID_GPIO (0x1234)
#define CAN_PERIOD_GPIO (0)
typedef struct __attribute__((__packed__)) {
	union bitfield {
		struct __attribute__((__packed__)) {
			unsigned int bms_fault:1;
			unsigned int bms_fault_latch:1;
			unsigned int HS_closed:1;
			unsigned int LS_closed:1;
			unsigned int shutdown_closed:1;
			unsigned int final_closed:1;
			unsigned int IMD_faulted:1;
			unsigned int IMD_fault_latched:1;
		};
		uint8_t AS_UINT;
	} bitfield;
} CAN_MSG_GPIO_T;


#define CAN_ID_BMS_analog_in_raw (0x2000000)
#define CAN_PERIOD_BMS_analog_in_raw (0)
typedef struct __attribute__((__packed__)) {
	uint16_t Vbat;
	uint16_t Vcar;
	uint16_t current_pos;
	uint16_t current_neg;
} CAN_MSG_BMS_analog_in_raw_T;


#define CAN_ID_BMS_current (0x2000001)
#define CAN_PERIOD_BMS_current (0)
typedef struct __attribute__((__packed__)) {
	float amps;
} CAN_MSG_BMS_current_T;


#define CAN_ID_BMS_contactor_volt_delta (0x2000002)
#define CAN_PERIOD_BMS_contactor_volt_delta (0)
typedef struct __attribute__((__packed__)) {
	float volts;
} CAN_MSG_BMS_contactor_volt_delta_T;


#define CAN_ID_BMS_status_1 (0x6b0)
#define CAN_PERIOD_BMS_status_1 (0)
typedef struct __attribute__((__packed__)) {
	uint8_t fake;
	int16_t pack_current;
	int16_t pack_voltage;
	uint8_t pack_soc;
	union status_1_bitfield {
		struct __attribute__((__packed__)) {
			unsigned int MPI2_state:1;
			unsigned int MPI3_state:1;
			unsigned int MPO2_state:1;
			unsigned int MPO3_state:1;
			unsigned int MPO4_state:1;
			unsigned int MP_enable_state:1;
			unsigned int MPO1_state:1;
			unsigned int discharge_relay_state:1;
			unsigned int charge_relay_state:1;
			unsigned int charger_safety_state:1;
			unsigned int MIL_state:1;
			unsigned int MPI1_state:1;
			unsigned int alwayson_state:1;
			unsigned int is_ready_state:1;
			unsigned int is_charging_state:1;
			unsigned int pad15:1;
		};
		uint16_t AS_UINT;
	} status_1_bitfield;
} CAN_MSG_BMS_status_1_T;


#define CAN_ID_BMS_status_2 (0x6b1)
#define CAN_PERIOD_BMS_status_2 (0)
typedef struct __attribute__((__packed__)) {
	uint8_t fake;
	uint16_t pack_DCL;
	int8_t pack_CCL;
	int8_t pack_high_temp;
	int8_t pack_low_temp;
} CAN_MSG_BMS_status_2_T;


// Messages from node (1): INVERTER
#define CAN_ID_placeholder (0x10000)
#define CAN_PERIOD_placeholder (0)
typedef struct __attribute__((__packed__)) {
	uint16_t fake;
} CAN_MSG_placeholder_T;


// Messages from node (2): VCU
#define CAN_ID_VCU_pedals (0x20000)
#define CAN_PERIOD_VCU_pedals (0)
typedef struct __attribute__((__packed__)) {
	uint16_t APPS1;
	uint16_t APPS2;
	uint16_t BRAKE;
	uint16_t EXTRA;
} CAN_MSG_VCU_pedals_T;


#define CAN_ID_VCU_switches (0x20001)
#define CAN_PERIOD_VCU_switches (0)
typedef struct __attribute__((__packed__)) {
	union switch_bitfield {
		struct __attribute__((__packed__)) {
			unsigned int button1:1;
			unsigned int button2:1;
			unsigned int button3:1;
			unsigned int button4:1;
			unsigned int button5:1;
			unsigned int button6:1;
			unsigned int button7:1;
			unsigned int button8:1;
		};
		uint8_t AS_UINT;
	} switch_bitfield;
} CAN_MSG_VCU_switches_T;



#endif /* LHRE_SHARED_CAN_DEFS_H_ */
